### ISSUE TITLE
License in package.json files

### ISSUE THREAD

**Issue by tkuhrt** [openwallet-foundation-labs/vc-api#16]
Can you confirm whether the license in the following package.json files should be updated?
* `apps/vc-api/package.json`
*  `libraries/did/package.json`
*  `libraries/webkms/package.json`

**Comment by jrhender** [comment]
Yes, they should be. Thanks for catching. In hindsight, I could have done a simple search could have caught the `gpl` instances 😬 .

**Comment by jrhender** [comment]
I went ahead and merged+closed this issue as I think it's a straightforward change but please reopen if necessary @tkuhrt

**Comment by tkuhrt** [comment]
LGTM. Thanks @jrhender for fixing.
